### ISSUE TITLE
Nylas-mail without Nylas ID

### ISSUE THREAD

**Issue by Karlsoost** [nylas-mail-lives/nylas-mail#1]
Hi all,

I'm looking for a smart mail for a Linux environment for a long time. Nylas looks still very promising to me. But the lack of support and the enforcement to use a Nylas ID is clearly holding me up.

As you obviously plan to bring that tool back to life, is there a plan to make it completely independently and freely usable without registering a Nylas ID?

Thanks a lot,
Karlsoost

**Comment by tsikerdekis** [comment]
+1 disabling the ID requirement shouldn't be difficult

**Comment by dweremeichik** [comment]
Just a heads up, the use of the Nylas API is still being discussed in Slack. Once that is figured out, this can be approached.

**Comment by kolya-ay** [comment]
Still figuring out the meaning of the phrase

> But the local sync engine in Nylas Mail means you don't need sync-engine.

From here nylas/sync-engine#448

**Comment by dweremeichik** [comment]
Closing this issue in favor of the more productive conversation on #30
