### ISSUE TITLE
Modify Existing Theme

### ISSUE THREAD

**Issue by lamixer** [nylas-mail-lives/nylas-mail#102]
Hello: I read Nylas-Mail is skinned using css. I'm no master, but I can read css to some extent, so I'd like to try to modify an exiting theme but I can't find them anywhere in my installation (Linux). 

Any suggestions?

Mostly I just need to make text bigger so I can read it on my screen. Thank you.

**Comment by step21** [comment]
Hi, I am not entirely sure if modifying in place is a good idea - they might get overwritten on updates. Instead I would suggest that you copy the starter theme (https://github.com/nylas/nylas-mail-theme-starter) or an existing theme and rename it, then install it as a new theme. That way, it will never be overwritten or similar. The theme files can be found on github under `/packages/client-app/internal_packages/` and then look for those with `ui-` these are the themes. The Ubuntu theme is for example here:
https://github.com/nylas-mail-lives/nylas-mail/tree/18545f3add6cefe2af36ae80f5dd427bb1752ad2/packages/client-app/internal_packages/ui-ubuntu
One problem might be that these are written in 'less' which is an abstraction of css that is then compiled into regular css, but it should still be relatively easy to use if you know css.
Alternatively, maybe if you try one of the existing community themes, one of them might already have bigger text that suits you.
