### ISSUE TITLE
Handle Sudden Stop

### ISSUE THREAD

**Issue by mrRosset** [nylas-mail-lives/nylas-mail#103]
My computer has a problem and can sometimes "lock up" when waking from sleep. I then have to do a hard reset. Everytime this has happend with nylas opened the nylas config has become corrupted.
I had 2 times a null config.json (by that I mean a file with a size of 4k but filled only with the byte 0).
And once it displayed an error about an invalid token in one of the config.xxxx.json (Sorry I didn't took a screenshot).

And everytime I had to re-add all my emails accounts, let it re-sync, ...

Would it be possible to correctly handle a sudden stop of the application ?

### Specs
**OS**: Windows 10, 1704, x64
**Nylas version**:  2.2.0 
I had between 4-5 emails accounts configured everytime this happened.

**Comment by seesemichaelj** [comment]
Those multiple config files were the first attempt to fix this problem. It's not a sudden stop of the program, but issues with writing to the disk. You could have tried saying "try older configuration". We keep the last ten versions of config.json (a version is written several times a minute).

However I noticed that 10 files sometimes isn't enough; I have been running NML in a VM and noticed that if the VM crashes, the 10 files are all corrupt.

In the meantime while we come up with a better solution, you can do the try older version thing (eventually you'll see the version number not change which means there's no more older ones). You should also make a copy of a config.xxx.json file once you have a stable setup of accounts. You can find it at ~/.nylas-mail/config.xxx.json (Linux/Mac) or c:\users\youruser\.nylas-mail\config.xxx.json. I suggest copying the file to the same directory as "config.json" with no timestamp in the middle. If the issue arrises again, you can delete all of the config.xxx.json files and NML should use the config.json as an initial file

**Comment by seesemichaelj** [comment]
FYI this has been a large issue that's been around for several months. Actually it was one of the drivers for forking Nylas since they stopped taking PRs months ago

**Comment by mrRosset** [comment]
You are right. I forgot to mention that in all cases, doing "try older configuration" did not work. As you said if it crash then the 10 files are corrupted.

I don't undertsand why all of them are being corrupted tho. Does Nylas keep all of those files open when it runs ? Could it not open them and perdiodically create a backup of the save and delete all the extra (> 10) ones from disk.

**Comment by seesemichaelj** [comment]
No it only opens the most recent one. Before there was only one config.json file. Now, we never write over an existing file; we create a new file and delete the extra ones to leave 10. There is some things that we can definitely do like what you suggest.

Further I think this is a write issue more than a read issue. The fact we write several files in a minute defeats the whole purpose of having a database vs config file lol

**Comment by seesemichaelj** [comment]
I'm probably good for doing this one since I made the first fix, but I'm open if another contributor wants to take over this one

**Comment by jrc2** [comment]
@seesemichaelj Is there any way I can backup my config in case this happens? I've had it happen twice now and reentering all my accounts is quite tedious with 2FA. It only happens of there's a power glitch that cuts off my computer or if I accidently tun off the power strip.

**Comment by seesemichaelj** [comment]
Yup:

> In the meantime while we come up with a better solution, you can do the try older version thing (eventually you'll see the version number not change which means there's no more older ones). You should also make a copy of a config.xxx.json file once you have a stable setup of accounts. You can find it at ~/.nylas-mail/config.xxx.json (Linux/Mac) or c:\users\youruser.nylas-mail\config.xxx.json. I suggest copying the file to the same directory as "config.json" with no timestamp in the middle. If the issue arrises again, you can delete all of the config.xxx.json files and NML should use the config.json as an initial file

**Comment by jrc2** [comment]
@seesemichaelj Oops, I missed that part! I tried the older version button, but none of the saved versions worked. I'll make a backup of it this time once I get everything set back up.Thank you!

**Comment by seesemichaelj** [comment]
@mrRosset @jrc2 I think I have a potential fix for this that was merged into master. We're releasing the next build (v2.2.2) in the first week of November which will have this. In the meantime, if you have a build environment set up, it would be great for you guys to test to see if this does anything or not in your circumstances.

Thanks!

**Comment by mrRosset** [comment]
Just want to add that after testing for a month it doesn't happens anymore. I had multiple crashed and I never completly lost the config.

**Comment by seesemichaelj** [comment]
@mrRosset Thanks for the update! Glad to hear!!! Please let us know if you have anymore issues
