### ISSUE TITLE
Editing signatures in raw HTML UI Glitch

### ISSUE THREAD

**Issue by arjove** [nylas-mail-lives/nylas-mail#105]
Hi, 

I just installed the  latest version, and came across this glitch: 
![2017-10-07 17_57_48-netflix](https://user-images.githubusercontent.com/3273394/31309613-38b7836e-ab89-11e7-81d2-910d1e10b454.png)

When editing in raw html the input field becomes small.

**Comment by dweremeichik** [comment]
Yup! This has been an issue for a while, I just prompted a few people in the old Nylas repo to submit their PRs here. I'll link those in and your welcome to make the PR yourself if you'd like. Happy hacktoberfest!

**Comment by dweremeichik** [comment]
https://github.com/nylas/nylas-mail/pull/3622
https://github.com/nylas/nylas-mail/pull/3238
