### ISSUE TITLE
Quit Nylas Mail and workers

### ISSUE THREAD

**Issue by lamixer** [nylas-mail-lives/nylas-mail#109]
Hello ... forgive me if there is a way that I haven't discovered, but it seems if one runs Nylas-Mail (I'm on Linux) then quits it, several background 'helper' apps keep running (Nylas Mail Work, Nylas Mail emptyWindow, and another one maybe just Nylas). Besides restarting my computer, or maybe killing them by PID, there seems no way to stop them.

Maybe there should be a menu item separate from a normal Quit that says 'Quit Nylas and Background Helpers' or something like that.

Or maybe on Linux Nylas-Mail should be a systemd service.

This would free up memory and CPU time if one does not need email but maybe needs to maximize battery run time.

**Comment by seesemichaelj** [comment]
All OS's have these background processes. These mainly are for the sync processes to keep your DB up to date. You can press Ctrl+Q for Windows and Linux (Command+Q for Mac) to quit the app and background processes I believe (I'm out of town and can't check but I'm fairly certain).

There is a hidden menu bar for all systems if you press Alt, here I think File>Quit is the Ctrl+Q quit.

I will say that Windows has a menu in the top right that would be useful in Linux that I think has the quit option.

**Comment by lamixer** [comment]
Gnome 3 has has a top menu bar with a Quit option (that's the only option there), that is how I quit Nylas. I did eventually find the hidden menu (it needs to be changed so it's not so hidden, but that's another issue) and just now I tried to Quit Nylas with THAT quit menu, and it does take the background helpers with it. 

That's good.

So then, at some point you need to either remove the Quit menu from the Gnome 3 system menu bar or make it work the same as the Quit from the hidden 'File' menu.

(I just double-checked, and it again happens if I run Nylas then quit it from the system menu bar the background helpers do not quit. Fedora 26, installed from your RPM, v2.20)

**Comment by seesemichaelj** [comment]
Can you send a screenshot of the Gnome 3 menu you speak of?

The menu is hidden because it's a power user/developer menu that happens to have things that are (and should be) accessible to normal users. We probably won't make that menu less hidden but put it somewhere in documentation.

But we're open to making the normal UI more intuitive for standard functions like this

**Comment by lamixer** [comment]
Yes, being able to add an account and get to the preferences should not be so well hidden!
![fedora-gnome3-quit-menu](https://user-images.githubusercontent.com/4958776/31320319-8c4990e4-ac6a-11e7-887b-ced53ff0dde8.jpg)


There's the image... It is the upper left corner of the screen.

**Comment by seesemichaelj** [comment]
Cool thanks. I'll open an issue later tonight or tomorrow to make this UI better

**Comment by lamixer** [comment]
Don't forget! Really, if this menu in also used on other linux desktop environments, maybe you should move all the 'non-devloper' menu items to there, possibly nested if possible/necessary. At least it would be a good place to put the menu to open Preferences. Or this menu could be a non-hidden way to show the other menu bar ... instead of Quit it would be a menu bar toggle.

Other options that make sense to me: remove it completely, or make it quit properly like the hidden menu quit does.

**Comment by dweremeichik** [comment]
@seesemichaelj I dont believe that the hidden menu bar is actually for power users. This behavior is because it is an electron app, and this is how atom behaves. For example, there is no other way to get to the account preferences without using that menu. I believe the menu is visible by default on Windows. Correct me if I'm wrong here, I don't run on Windows much anymore.

**Comment by seesemichaelj** [comment]
The hidden menu is not visible by default on Windows (just verified with fresh install), and I don't think it's default on any OS.

I can understand that it isn't for power users, but no where do we ever say "Press Alt to do more advanced stuff". Let alone, if it was intended for all users, it should look nice and within theme (it does not using the default theme). This is why there is a hamburger menu in Windows.

**Comment by seesemichaelj** [comment]
See below:

![image](https://user-images.githubusercontent.com/549323/31367773-974a9456-ad47-11e7-8c87-2379b7cb343a.png)

**Comment by dweremeichik** [comment]
Oh wow, shit has changed since N1. I stand very corrected.

**Comment by seesemichaelj** [comment]
@lamixer have you been able to update to v2.2.1 yet? Does this issue still exist in that version?

**Comment by seesemichaelj** [comment]
i veriied t his is still happening. not sure why i commented on the old issue
