### ISSUE TITLE
Enable Hamburger Menu on Linux

### ISSUE THREAD

**Issue by seesemichaelj** [nylas-mail-lives/nylas-mail#112]
@lamixer opened #109 because using the Quit function in the Gnome panel menu for Nylas did not exit all of the Nylas workers. This brings up a much bigger issue: the Linux UI does not have an intuitive menu outside of the hidden developer menu (which requires Alt to show). The only way to access preferences in Nylas on Linux (maybe Mac?) is by click the arrow next to All Accounts and clicking to add or manage accounts. Windows has a hamburger menu button in the top right which provides some useful information.

This issue is to enable hamburger menu on Linux (and Mac if Mac doesn't have it).

**Comment by dweremeichik** [comment]
See my comment in #109 I don't think that menu is meant to be developer only.

**Comment by seesemichaelj** [comment]
Regardless if it's not meant to be developer only, it is not known by the normal user and we have no intentions on making this a normal user thing to know, which means we should add a button to access some of these features

**Comment by dweremeichik** [comment]
Yup, I stand corrected. Hamburger menu sounds like a good idea.

**Comment by LiHRaM** [comment]
Hey guys. I've already halfway-solved this problem. I'd love to take this one.
