### ISSUE TITLE
Do you want to collect crash reports?

### ISSUE THREAD

**Issue by step21** [nylas-mail-lives/nylas-mail#117]
Currently, in the application ( nylas-mail/packages/client-app/src/browser/application.es6 ) there is 

```
app.on('ready', () => {
      crashReporter.start({
        productName: 'Nylas Mail',
        companyName: 'Nylas, Inc.',
        submitURL: 'https://nylas-breakpad-sentry.herokuapp.com/crashreport',
        autoSubmit: true,
      });
});
```

So assuming this is still active, do you want to keep it this way, or change it to another endpoint?

**Comment by dweremeichik** [comment]
That's a very good question, we certainly should not continue sending them to Nylas.

**Comment by step21** [comment]
I mean, maybe that is turned off anyway or they never check, who knows.

**Comment by dweremeichik** [comment]
It seems like this is what they had on heroku: https://github.com/khamidou/electron-breakpad-sentry

**Comment by dweremeichik** [comment]
If we decide we want to enable this, sentry does support OSS projects. What are your thoughts @seesemichaelj ?

**Comment by seesemichaelj** [comment]
definitely stop sending it to them. would be nice to have if we were big scale. dont think anyone would look at them for months to come? if people have problems, they find the github

**Comment by step21** [comment]
So... maybe comment out for now? Tbh I didn't actually check if this is still run.

**Comment by dweremeichik** [comment]
Oh, this is still run, it fires on the ready event.

**Comment by dweremeichik** [comment]
I think commenting it out is fine for now.

**Comment by seesemichaelj** [comment]
Yup sounds good
