### ISSUE TITLE
Support for Custom Ports

### ISSUE THREAD

**Issue by 54** [nylas-mail-lives/nylas-mail#120]
Hey!

It would be great if someone could add support for non-standard ports when configuring an email account. In my particular case, it makes it mildly annoying to use ProtonMail as their bridge software defaults to 1143 and 1025 for the incoming/outgoing ports.

Also, this affects signifcantly more people than simply ProtonMail users. Many organizations change their mail server ports—which makes Nylas unusable without using inspect element or something. See: nylas/nylas-mail#3424

**Comment by 54** [comment]
Added a small bounty: [![current bounty](https://api.bountysource.com/badge/issue?issue_id=50284715)](https://www.bountysource.com/issues/50284715-support-for-custom-ports)

**Comment by 54** [comment]
Pinging @axelvnk - Hey! I saw that you made a pull request on the main *Nylas Mail* repository (nylas/nylas-mail#3640). It doesn't appear that there is any real activity there, though. 

Figured I'd see if you would like to make that pull request here before I go ahead and make my own.

**Comment by axelvnk** [comment]
@54 I'll do it tonight :)

**Comment by kaustav1996** [comment]
@axelvnk did you do it?

**Comment by seesemichaelj** [comment]
@dweremeichik would you want this to remove the dropdown in place of a text field for port number? Or would we rather have the dropdown with "Custom..." which shows the input field and allows for input? The latter I think is better, but will require some extra work

**Comment by dweremeichik** [comment]
I'm behind the latter. The other option allows for too much error. It's hard enough for most to set up email as it is. 
To be honest there has been times when I have forgotten which port my provider used in the past, simple solution was to try each available option. Can't do that with a text box.

**Comment by seesemichaelj** [comment]
agreed; therefore i dont think the PR at https://github.com/nylas/nylas-mail/pull/3640 is sufficient. i've got some time tonight to work this. still need my 4 PRs for the month >.>

**Comment by seesemichaelj** [comment]
i went ahead and started this

**Comment by seesemichaelj** [comment]
Here's what it looks like:

![peek 2017-10-25 23-20](https://user-images.githubusercontent.com/549323/32033593-4f442d0c-b9db-11e7-8850-db284378c99d.gif)

**Comment by dweremeichik** [comment]
Well done! I'm :+1: on this.
