### ISSUE TITLE
Custom IMAP / SMTP Ports

### ISSUE THREAD

**Issue by andrewparadi** [nylas-mail-lives/nylas-mail#137]
This has recently been implemented in Mailspring but I'd love to see it implemented here since I'd much prefer to use the open source fork of Nylas. I have more than 4 accounts and Mailspring is going to start charging me. If I have a chance I'll dig in and try to fix this myself.

**Comment by seesemichaelj** [comment]
This was closed last night: https://github.com/nylas-mail-lives/nylas-mail/issues/120

Should be in the upcoming 2.2.2 build (first week of November)

**Comment by seesemichaelj** [comment]
There are plenty of other things here and there though that we need people on! Also feel free to hit us up on slack (invite url in readme) with any questions

**Comment by andrewparadi** [comment]
@seesemichaelj thanks for the quick update! Great to see this repo is still really active. Sure thing, I'll hop on Slack and see where I can help in the months to come.
