### ISSUE TITLE
Fix Slack Invite URL on README.md

### ISSUE THREAD

**Issue by seesemichaelj** [nylas-mail-lives/nylas-mail#14]
Currently the URL for the new Slack team (https://join.slack.com/nylasisalive/shared_invite/MTg4MzQzMzY3NDEyLTE0OTU3NTQwNDMtYzhhZmE3NDM0NA) is no longer valid; the invite URL should be updated

**Comment by dweremeichik** [comment]
Per @danielmelogpi the new link is:
https://join.slack.com/nylasisalive/shared_invite/MTkyNTkyNzMwODA1LTE0OTY2MjIyMDQtMWNhNzI0NWM4Mg

**Comment by dweremeichik** [comment]
Perhaps we should consider using an automated inviter?

**Comment by seesemichaelj** [comment]
I'm not sure what you mean by automated; it seemed pretty automated when I signed up and required no approval (that I was aware of).

If there isn't any approval process currently, I don't think we need anything else.

**Comment by dweremeichik** [comment]
Sorry, meant to @ @danielmelogpi, he mentioned in his PR that the link expires every 30 days, which is less than ideal. There are systems out there that essentially send you an invite when you enter your email. The benefit is that we don't have to update the readme every month. The down side is we have to host it somewhere.

**Comment by seesemichaelj** [comment]
Ah. I think running https://github.com/outsideris/slack-invite-automation on a free Heroku dyno may be sufficient for this kind of daemon for the meantime

**Comment by dweremeichik** [comment]
Awesome! When those free dynos fall asleep, is there some intervention needed to wake them up? Never used heroku before.

**Comment by seesemichaelj** [comment]
Heroku's backend will automatically wake it up when it receives web traffic for it. They're just not good for high intensity, always on, high performance services. They're great for little things that do small tasks here and there. You're just limited on the number of hours per month per account (not per dyno/application) at 550 hours per month. This app should barely get any webtraffic per day.

**Comment by philip-ulrich** [comment]
We should just use stacktodo: https://stacktodo.com/tools/invite

**Comment by seesemichaelj** [comment]
Stacktodo totally looks feasible too. They basically are doing the hosting and we're just using their bot. Doesn't look like it costs anything

**Comment by dweremeichik** [comment]
@philip-ulrich, feel free to give it a shot.

**Comment by philip-ulrich** [comment]
Yeah, it's free. I use it for another slack of mine. I'll install it, but I'll need you to do a couple things @dweremeichik. I'll just ping you on slack.

**Comment by dweremeichik** [comment]
@philip-ulrich It may not be free, see directly below the image [here](https://stacktodo.com/#client-banner)

**Comment by philip-ulrich** [comment]
Oh. They must have changed things since I started using it then. Good to know! That might be why it wasn't joining then. I guess we need to look at implementing the Heroku solution then.

**Comment by hassec** [comment]
Hi just wondering if there is a specific reason why slack was chosen over [Gitter](https://gitter.im/)?   
AFAIK we would be able to avoid the annoying invite problem and also the amount of messages wouldn't be limited to 10k..   

Lastly while the slack channel is still this new and the community isn't that big yet a move shouldn't be that complicated, no?

**Comment by danielmelogpi** [comment]
@hassec , no real reason. Slack just came to mind that day. 
As I see, Gitter could also be a good fit for this.

@dweremeichik , yeah, we are less then ideal on this matter. :/ change that every month is bad

**Comment by mayurdw** [comment]
We have heaps of options in this, I use discord for other groups in which I can get a private server for my chat 

Before we go ahead with changing the link though, I think we need to limit the number of people who are participating in the slack chat right now. The group has 32 members and it keeps getting bigger

We could create a different account (Gitter for example) for random joines and use slack (current chat) for contributers

**Comment by hassec** [comment]
Yes we definitely have tons of options.

I just pointed out Gitter as I like how easy it is for people to join ( given you have a github account which I think we can assume..).   

As far as two different groups  I personally think it's easier to just use one solution. We can still have multiple rooms for different purposes in Gitter.

**Comment by danielmelogpi** [comment]
@mayurdw, not sure if a split would be better. We can always have reserved conversation in rooms or channels (depending on the tool).

Do you see any problem with too many people joining (assuming most of them never came back after the first interaction)? I am genuinely asking. First time on this opensource world.

**Comment by mayurdw** [comment]
@danielmelogpi no there is no problem with too many people

**Comment by hassec** [comment]
Well I guess we should just discuss with everyone currently involved and see what our options are and then just vote on what we will choose... no?     
Maybe we should have that discussion on slack though so everyone notices it.

**Comment by claudioruiz** [comment]
I can volunteer myself into updating the whole README to allow people willing to contribute into contribute.

**Comment by seesemichaelj** [comment]
I'm confused what you're offering @claudioruiz I'm not sure the README needs updating to allow people to contribute?

**Comment by claudioruiz** [comment]
@seesemichaelj sorry, I meant the Readme looks fairly similar than the original project, as far we are still talking about how to deal with the fork process with Nylas team. So I guess it would be nice to say that upfront on the ReadMe to avoid people thinking this is a _working and active_ fork, which still it isn't.

**Comment by mayurdw** [comment]
@claudioruiz thanks for getting to it but the readme already mentions that this is a fork. Updating the readme was done a while back

**Comment by claudioruiz** [comment]
@mayurdw understood, but at a very first sight, still looks very similar and we are trying to have a fork. Anyway, it was just an offer, no big deal ;)

**Comment by dweremeichik** [comment]
@claudioruiz what changes do you propose to make it more clear?

**Comment by Kabouik** [comment]
Would it be possible for you guys to have an IRC channel as well for quick questions from people trying to use the fork (but have no skills for contributing to the development itself)? Or Slack would be fine as well, but the access is currently restricted and I believe IRC, Freenode in particular, is still a pretty common place for that kind of things, and it would avoid cluttering the Slack channel with too many inactive users logging in just once in a blue moon to ask a question.

**Comment by seesemichaelj** [comment]
We have finalized on using Slack as our communication channel. I believe it is okay to have too many inactive users on the Slack channel. We can create a noob channel if necessary. I don't believe Slack access is currently restricted. I just updated the Slack invite URL which should let you join: https://github.com/nylas-mail-lives/nylas-mail/blob/master/README.md
