### ISSUE TITLE
The URL is not correctly linked

### ISSUE THREAD

**Issue by kometchtech** [nylas-mail-lives/nylas-mail#143]
As shown in the image, it seems that "?" Is not correctly encoded, or it is a URL, but the subsequent character string is not correctly recognized as a URL.

I will paste the email of Amazon.co.jp for reference.

![shipment](https://user-images.githubusercontent.com/5137077/32135391-76611ad4-bc39-11e7-9fb1-732056493191.JPG)

Env:
- Windows 10 Pro 1709
- Nylas Mail 2.2.1

**Comment by nirmit** [comment]
Maybe, it’s because the regex finds the “=“ before the ? And ends the match.  I will look into it.

**Comment by seesemichaelj** [comment]
This will be v2.2.2 in the first week of November. Going to test the master branch to ensure #145 fixed this and other links werent broken
