### ISSUE TITLE
Lots of Words Being Processed as URLs

### ISSUE THREAD

**Issue by seesemichaelj** [nylas-mail-lives/nylas-mail#147]
FYI is turned into a link?
![image](https://user-images.githubusercontent.com/549323/32238118-4fdacf9e-be3d-11e7-93c0-ee67f7ddcca0.png)

I'm guessing this is an issue with the new URL regex that went into #145. Can you take a look into this @nirmit? The URL (when copying link address in Nylas) was `http://FYI`

**Comment by seesemichaelj** [comment]
it seems to be the first word of every paragraph maybe?
![image](https://user-images.githubusercontent.com/549323/32238269-c0eaa614-be3d-11e7-97b3-f5235c33b146.png)

**Comment by nirmit** [comment]
Sure.. looking into it right now
