### ISSUE TITLE
Add Mail Rules

### ISSUE THREAD

**Issue by nirmit** [nylas-mail-lives/nylas-mail#157]
Need to add back the mail rules preferences so that emails can be organized, classified or trashed based on certain conditions.

**Comment by seesemichaelj** [comment]
Before anyone implements this, please discuss on this Issue about your approach to make sure we're good with it

**Comment by nirmit** [comment]
@seesemichaelj - I was wondering if we can get mail rules preferences activated again!  

See below:
<img width="1249" alt="screen shot 2017-11-06 at 5 58 38 pm" src="https://user-images.githubusercontent.com/431140/32468448-4acade8e-c31c-11e7-9cc4-2cafcd5a42f5.png">

**Comment by seesemichaelj** [comment]
oh your issue didn't really state that it was existing thing. i'm guessing thats a plugin? does it work?

**Comment by nirmit** [comment]
Yes!  It does.  I wonder why this was removed when it works and can be immensely helpful!
