### ISSUE TITLE
Email Snooze Feature Error: Cannot read property 'feature_usage' of null

### ISSUE THREAD

**Issue by metinn** [nylas-mail-lives/nylas-mail#159]
i am getting this error when trying to snooze an email with swipe gesture.

> Sorry we were unable to save your snooze settings. Cannot read propery 'feature_usage' of null

<img width="532" alt="screen shot 2017-11-07 at 11 29 05" src="https://user-images.githubusercontent.com/1876064/32486136-cdb36c90-c3b6-11e7-9336-b467f1b82193.png">

**Comment by dweremeichik** [comment]
Appears to be related to Nylas's feature usage restriction. Do you have a Nylas account?

**Comment by metinn** [comment]
No, i dont have Nylas account. Is account required for snooze feature?

**Comment by dweremeichik** [comment]
I believe that is currently the case. @simonft can verify I think.

**Comment by simonft** [comment]
As best as I can tell, snoozing the message (moving it into a hidden folder) is done client side, but unsnoozing it after the time is up is done in server side workers we aren't running. @dweremeichik thoughts on whether we should just pull the code out, or add an option for whether people run it themselves?

**Comment by simonft** [comment]
The only things that use this are the plugins for send later, send reminders, and snooze. Since I don't think we want to commit to maintaining the cloud code for these, I suggest we remove the internal package for it (and possibly those plugins as well, unless we have a good story for making them work).

**Comment by nirmit** [comment]
@simonft - Given that the metadata is available locally, should we not update it to handle locally as well.  We can add a worker to monitor the snoozed messages list and push them back into the INBOX as unread at the time set in the metadata.  Thoughts?

**Comment by simonft** [comment]
Yeah, that's a good point. It shouldn't be too hard to add something to the sync-worker package to move them back.

**Comment by dweremeichik** [comment]
@simonft I believe Ben even went this way with Mailspring due to security concerns.

**Comment by dweremeichik** [comment]
Not sure why I marked this as in progress...

**Comment by nirmit** [comment]
Well, you can keep it marked as *in progress*, @dweremeichik  :)

**Comment by seesemichaelj** [comment]
@dweremeichik you marked it in progress because nirmit attempted a solution in #160 (that we denied)

**Comment by nirmit** [comment]
@seesemichaelj Can you please close this issue as well?  It seems that #174 only closed #122
