### ISSUE TITLE
Preferences menu item not available on Mac OSX

### ISSUE THREAD

**Issue by nirmit** [nylas-mail-lives/nylas-mail#168]
The Preferences Menu link is not available on MacOS anymore.  The one in 2.2.1 was working correctly.  Please see the menu link from v. 2.2.1 below:
<img width="244" alt="need this" src="https://user-images.githubusercontent.com/431140/32728292-bba0e488-c84d-11e7-843c-52093fb1976c.png">

**Are there any related issues?**
None.

**What operating system are you using?**
Mac OSX Sierra (10.12.6)

**What version of Nylas Mail are you using?**
2.2.2

**Feature Request?**
No.

**Additional Information**
Please see the screenshots below.

<img width="660" alt="screen shot 2017-11-13 at 8 27 23 am" src="https://user-images.githubusercontent.com/431140/32728194-67f9e230-c84d-11e7-8be1-d5703a76c4e8.png">
<img width="292" alt="screen shot 2017-11-13 at 8 27 27 am" src="https://user-images.githubusercontent.com/431140/32728195-680af584-c84d-11e7-8cf8-aafa8f835cf1.png">
<img width="592" alt="screen shot 2017-11-13 at 8 27 30 am" src="https://user-images.githubusercontent.com/431140/32728196-681d40b8-c84d-11e7-972a-da9d37cad9bf.png">
<img width="545" alt="screen shot 2017-11-13 at 8 27 31 am" src="https://user-images.githubusercontent.com/431140/32728197-68305414-c84d-11e7-8f47-31f07201c95b.png">
<img width="544" alt="screen shot 2017-11-13 at 8 27 33 am" src="https://user-images.githubusercontent.com/431140/32728198-68431b58-c84d-11e7-9d96-96941f546b9c.png">
<img width="583" alt="screen shot 2017-11-13 at 8 27 34 am" src="https://user-images.githubusercontent.com/431140/32728199-6855460c-c84d-11e7-9638-5b04b43ff13f.png">
<img width="554" alt="screen shot 2017-11-13 at 8 27 36 am" src="https://user-images.githubusercontent.com/431140/32728200-686122ec-c84d-11e7-85b7-0632bd1cc73f.png">

**Comment by maartenvang** [comment]
Priority Low? This is a very annoying issue. I can confirm that I have this issue too, on the latest version.

**Comment by nirmit** [comment]
@maartenvang I have submitted a PR.  In the meantime, to access preferences, you can use `cmd + ,`.

**Comment by nirmit** [comment]
@maartenvang This is available in 2.2.2-4alpha.
