### ISSUE TITLE
Refine Linux build docs. 

### ISSUE THREAD

**Issue by dweremeichik** [nylas-mail-lives/nylas-mail#17]
The linux build docs need some rework. Version needs to be 6.9 for node. Environment variables need to be set.

**Comment by seesemichaelj** [comment]
are we sure they need to be 6.9? i've been building with 6.11.0 apparently

**Comment by dweremeichik** [comment]
Travis builds using 6.9. Builds fail with >=7 which there is an issue for in the original repo. I believe this is due to node-gyp.

**Comment by seesemichaelj** [comment]
Alright; I guess these are the instructions which is "the bible". I know that it works on > 6.9 as I don't build with 6.9.

**Comment by dweremeichik** [comment]
I believe we have also seen issues with 6.4 not 100% sure as I didn't see it myself. My view on it: "yes it is older, I personally use newer. When I try to use newer and it breaks, I can slap myself for not RTFM." If people build successfully with newer, I'm cool with it. If the repo builds with newer, we bump the version in the docs. NVM makes this a very non-issue, as it is dead simple to change versions. Windows even has a "version" of NVM now.

I am also open to making it a range if we can prove that it works fine on all the versions in that range.

**Comment by dweremeichik** [comment]
Also, found the issue in the Nylas repo: https://github.com/nylas/nylas-mail/issues/3083

**Comment by seesemichaelj** [comment]
yup; i'm fine with your reasoning here

**Comment by step21** [comment]
One thing, is there a way to prevent the building of deb and rpm packages? For dev use this would be preferable I think as that can take quite a while.

**Comment by seesemichaelj** [comment]
I agree with @step21, opened issue #44
