### ISSUE TITLE
'isomorphic-core' is not in the npm registry

### ISSUE THREAD

**Issue by MartinEden** [nylas-mail-lives/nylas-mail#170]
I attempted to get the client app running from source locally by following the instructions [here](https://github.com/nylas-mail-lives/nylas-mail/blob/master/docs/guide/contributing/installation.md).

I'm running Ubuntu 16.04 LTS, so I followed steps 1 & 2 [here](https://github.com/nylas-mail-lives/nylas-mail/blob/master/docs/guide/contributing/installation.md#linux----debainubuntu) and then skipped down to the [common steps](https://github.com/nylas-mail-lives/nylas-mail/blob/master/docs/guide/contributing/installation.md#common). I installed nvm, as described on the linked page, and then ran `nvm exec 6.9 npm install` in `packages/client-app`. This is the output I got:

```
Running node v6.9.5 (npm v3.10.10)
npm WARN deprecated mimelib@0.2.19: This module is deprecated
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated guid@0.0.10: Please use node-uuid instead. It is much better.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-mac-notifier@0.0.13 (node_modules/node-mac-notifier):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for node-mac-notifier@0.0.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/home/martin/.nvm/versions/node/v6.9.5/bin/node" "/home/martin/.nvm/versions/node/v6.9.5/bin/npm" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/isomorphic-core
npm ERR! 404 
npm ERR! 404  'isomorphic-core' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'nylas-mail'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/Dropbox/Code/js/nylas-mail/packages/client-app/npm-debug.log
```

I can attach `npm-debug.log` if that would be helpful, but it doesn't look to contain much more info.

**Comment by seesemichaelj** [comment]
Interesting, can you try running the commands `nvm use 6.9` and then `npm install`?

isomorphic-core is not a remote package, it's included in the source

**Comment by MartinEden** [comment]
I get the same output that way.

**Comment by dweremeichik** [comment]
You shouldn't have to run npm install inside the `packages/*` folders, only the top level folder.

**Comment by seesemichaelj** [comment]
Ah I missed that! Sorry! Ya, step 3 in the common instructions just says to go in to the base directory of the repo

**Comment by dweremeichik** [comment]
To be honest I'm not sure why isomorphic core is in that packages package.json file. It's possible that it is there because of the monorepo, or it is also possible that Nylas had an in house NPM repo. Either way, I don't think you need to call npm install in that folder.

**Comment by dweremeichik** [comment]
@seesmichaelj I almost missed it too... Lol

**Comment by seesemichaelj** [comment]
Open a new issue if you have other problems, but the above should fix the specific error here. thanks @MartinEden!

**Comment by MartinEden** [comment]
Yup that works. Sorry for misreading the docs!
