### ISSUE TITLE
'Nylas Mail work' listen on TCP *:2578

### ISSUE THREAD

**Issue by l2dy** [nylas-mail-lives/nylas-mail#172]
Fresh install of `nylas-mail-2.2.2.dmg` on macOS.

Why would a mail client listen on all addresses by default? This could be a security risk.

```
  PID STAT      TIME  SL  RE PAGEIN      VSZ    RSS   LIM     TSIZ  %CPU %MEM COMMAND
23841 S      0:07.11   0   0      0  5328628 228112     -        0   1.1  2.7 Nylas Mail work
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Nylas\x20 23841 admi   31u  IPv4 0xredactedredacted      0t0  TCP *:2578 (LISTEN)
```

**Comment by dweremeichik** [comment]
Not exactly sure what is going on here, there may be a reason for it. This needs investigation.

**Comment by dweremeichik** [comment]
Can confirm, this should be scoped to localhost: https://github.com/nylas-mail-lives/nylas-mail/search?utf8=✓&q=2578

**Comment by dweremeichik** [comment]
See the following on how to set the host: https://hapijs.com/tutorials/getting-started?lang=en_US

**Comment by l2dy** [comment]
@dweremeichik, can you review #173?

**Comment by l2dy** [comment]
The "Status: Pending" label should be replaced.

Any ETA for a new release?

**Comment by dweremeichik** [comment]
Debatable on the label, as a PR was merged and the issue was closed. As far as a release, there hasn't been any other major changes as of late that would necessarily warrant a release, let me see what can be done.

**Comment by nirmit** [comment]
@l2dy Part of 2.2.2-4alpha.
