### ISSUE TITLE
Sender name displayed in a confusing way

### ISSUE THREAD

**Issue by davdavf** [nylas-mail-lives/nylas-mail#179]
Just started using Nylas recently. Noticed some strange behavior in the display of sender and recipient names.

I receive email from recipients whose From information has the following format:

"First Last, Company" <first.last@domain.com>

Nylas displays sender, and recipient information, name as only "Company". This is quite confusing. Especially since both the sender is shown as "Company" and also other colleagues in CC are shown as "Company".
Or is this a setting that can be configured?

**Comment by nirmit** [comment]
@davdavf This is part of 2.2.2-4alpha.
