### ISSUE TITLE
Issue in FileDownloadStore that forces re-download of files

### ISSUE THREAD

**Issue by nirmit** [nylas-mail-lives/nylas-mail#189]
This is a weird issue that I have been facing but didn't have the time to dig into.  The way the `FileDownloadStore` checks, if the file is already downloaded, seems to be broken (or it's just me!).  

The `_checkForDownloadedFile` method checks for the file size in the `~/.nylas-mail/downloads` directory and the file size captured from the header.  If the file sizes are same, it won't initiate a download, else it would.  In my case, none of the attachments has the same file size (physical) as the size mentioned in the header!  Therefore, Nylas always re-downloads the file and re-write the physical one.  This also delays the availability of the attachment in case of large files.

Does this sound familiar?  Is anyone else facing the same issue?

**Comment by seesemichaelj** [comment]
I definitely will say the way downloads works in general seems kludgy. Many times the file is "downloaded" with 0 bytes; I have to quit nylas and that sometimes fixes it. It might be worth it to do a full review of the code and clean up stuff and make it stable. I don't know if my issue is similar to your issue however

**Comment by nirmit** [comment]
It happens to me almost all the time with *large* files (>2MB)... 

Also, can you please remove the `contributor wanted` label?
