### ISSUE TITLE
Can't send mail - substring undefined 

### ISSUE THREAD

**Issue by dweremeichik** [nylas-mail-lives/nylas-mail#19]
```sh
Cannot read property 'substring' of undefined
    at pathForBodyFile (message-body-utils.es6:32:21)
```
*See parent issues for details:*
Split from #15
Original https://github.com/nylas/nylas-mail/issues/3583

**Comment by tsikerdekis** [comment]
Was there any progress with this error?

**Comment by seesemichaelj** [comment]
the fix provided in commit 3885160 definitely prevents the crash but doesn't solve the problem.

i'm not sure if we care about solving the problem, nor am i sure we can.

however, further analyis shows message-utils.es6 line 430 does a Message.build(message) as if it is building the object in sequelize. the object "message" does include an id (see below):
`{"accountId":"1353772030cafdf74935591a357a90afcdc6957164eb0a9cdd11bad8b6aa77f2","threadId":null,"headerMessageId":"<local-78da9cd9-9e6b@nylas-mail.nylas.com>","from":[{"client_id":"local-b6293004-9036","account_id":"1353772030cafdf74935591a357a90afcdc6957164eb0a9cdd11bad8b6aa77f2","name":"Mike Seese","email":"seeseplusplus@gmail.com","thirdPartyData":{},"is_search_indexed":false,"id":"local-b6293004-9036"}],"to":[{"client_id":"local-37344b5d-e748","server_id":"0a657f6596f7ef0c56fa46637d8457259a4c709cdfebfe5e98206655c3ad82e3","object":"contact","account_id":"1353772030cafdf74935591a357a90afcdc6957164eb0a9cdd11bad8b6aa77f2","name":"Mike Seese","email":"seeseplusplus@gmail.com","thirdPartyData":{},"is_search_indexed":true,"search_index_id":1,"id":"0a657f6596f7ef0c56fa46637d8457259a4c709cdfebfe5e98206655c3ad82e3"}],"cc":[],"bcc":[],"replyTo":[],"subject":"","body":"<br><br><signature>Sent from <a href=\"https://nylas.com?ref=n1\">Nylas Mail</a>, the best free email app for work</signature>","unread":false,"isDraft":true,"isSent":false,"version":0,"date":"2017-06-29T04:22:16.858Z","uploads":[{"filename":"main.js","id":"local-d7d16f9a-4152","inline":false,"messageClientId":"local-78da9cd9-9e6b","originPath":"/home/mike/nylas-mail/packages/client-app/src/browser/main.js","size":7942,"stats":{"atime":"2017-06-29T01:28:11.146Z","birthtime":"2017-04-28T04:14:17.916Z","blksize":4096,"blocks":16,"ctime":"2017-04-28T04:14:17.916Z","dev":64512,"gid":1000,"ino":3317118,"mode":33204,"mtime":"2017-04-28T04:14:17.916Z","nlink":1,"rdev":0,"size":7942,"uid":1000},"targetDir":"/home/mike/.nylas-dev/uploads/local-78da9cd9-9e6b/local-d7d16f9a-4152","targetPath":"/home/mike/.nylas-dev/uploads/local-78da9cd9-9e6b/local-d7d16f9a-4152/main.js","uploadDir":"/home/mike/.nylas-dev/uploads"}],"id":"**4951192eed4899df2f174cf559f63238334ecbd8a0aa150280539682380c3966**"}`

however, for some reason, this id does not make it down to message-body-utils as it is "undefined" just before building the path (see object below):
`{"account_id":"1353772030cafdf74935591a357a90afcdc6957164eb0a9cdd11bad8b6aa77f2","object":"message","subject":"","to":[{"client_id":"local-37344b5d-e748","server_id":"0a657f6596f7ef0c56fa46637d8457259a4c709cdfebfe5e98206655c3ad82e3","object":"contact","account_id":"1353772030cafdf74935591a357a90afcdc6957164eb0a9cdd11bad8b6aa77f2","name":"Mike Seese","email":"seeseplusplus@gmail.com","thirdPartyData":{},"is_search_indexed":true,"search_index_id":1,"id":"0a657f6596f7ef0c56fa46637d8457259a4c709cdfebfe5e98206655c3ad82e3"}],"from":[{"client_id":"local-b6293004-9036","account_id":"1353772030cafdf74935591a357a90afcdc6957164eb0a9cdd11bad8b6aa77f2","name":"Mike Seese","email":"seeseplusplus@gmail.com","thirdPartyData":{},"is_search_indexed":false,"id":"local-b6293004-9036"}],"cc":[],"bcc":[],"reply_to":[],"date":null,"files":[],"folder":null,"labels":[],"thread_id":null,"message_id_header":"<local-78da9cd9-9e6b@nylas-mail.nylas.com>"}`

everything between the two points is sequelize code

**Comment by seesemichaelj** [comment]
with that said, we're using a custom branch of sequelize: https://github.com/nylas/sequelize/tree/nylas-3.40.0

**Comment by seesemichaelj** [comment]
i vote to ignore the root cause of this issues for now and revisit later in a new issue if other things start breaking.
