### ISSUE TITLE
Failed at the @paulcbetts/cld@2.4.6 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by taneher** [nylas-mail-lives/nylas-mail#203]
I'm trying to install nylas-mail following the [contribution/installation.md guide](https://github.com/nylas-mail-lives/nylas-mail/blob/master/docs/guide/contributing/installation.md#common) and get the error in the title when I run npm install on my system. (Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux). 
Attached is the [npm-debug.log](https://github.com/nylas-mail-lives/nylas-mail/files/1834887/npm-debug.log). 
The important bit would probably be

```
 5724 error Linux 4.9.0-6-amd64
 5725 error argv "/home/alex/.nvm/versions/node/v6.9.5/bin/node" "/home/alex/.nvm/versions/node/v6.9.5/bin/npm" "rebuild"
 5726 error node v6.9.5
 5727 error npm  v3.10.10
 5728 error code ELIFECYCLE
 5729 error @paulcbetts/cld@2.4.6 install: `node-gyp rebuild`
 5729 error Exit status 1
 5730 error Failed at the @paulcbetts/cld@2.4.6 install script 'node-gyp rebuild'.
 5730 error Make sure you have the latest version of node.js and npm installed.
 5730 error If you do, this is most likely a problem with the @paulcbetts/cld package,
 5730 error not with npm itself.
 5730 error Tell the author that this fails on your system:
 5730 error     node-gyp rebuild 
 5730 error You can get information on how to open an issue for this project with:
 5730 error     npm bugs @paulcbetts/cld
 5730 error Or if that isn't available, you can get their info via:
 5730 error     npm owner ls @paulcbetts/cld
 5730 error There is likely additional logging output above.
```

I'm using node v6.9.5 and npm v3.10.10. Also I've had to install g++-6 instead of 4.8 as 4.8 is (apparently) not supported on Debian 9.3 stable

**Comment by dweremeichik** [comment]
Haven't seen this one before. Could be due to the g++ version. In the event that npm is getting in the way with a bad package (sometimes it happens) you could try an `npm cache clean --force`. Then npm install again.

**Comment by seesemichaelj** [comment]
Closing this as we haven't heard from @taneher  whether or not the suggestion worked
