### ISSUE TITLE
ccccccicevufgrhcbfgcrggvfhctknbhiuhcjnhuhvbb

### ISSUE THREAD

**Issue by rucuriousyet** [nylas-mail-lives/nylas-mail#209]
- [ ] I have read the above warning completeley

**Comment by seesemichaelj** [comment]
did your cat get a hold of your keyboard? :cat:

**Comment by rucuriousyet** [comment]
Sorry, I was just testing my Yubikey. Apparently when you hold down the button on a browser it spits out random characters LOL

**Comment by rucuriousyet** [comment]
I didn't realize it submited the issue either lol

**Comment by seesemichaelj** [comment]
no worries!
