### ISSUE TITLE
Test needs to be created for reversing the order for conversations

### ISSUE THREAD

**Issue by tsikerdekis** [nylas-mail-lives/nylas-mail#27]
Probably this will entail a review of existing tests. 3 of them are failing but I have not clue what they are.

**Comment by tsikerdekis** [comment]
Note to self: tests are located at nylas-mail/packages/client-app/internal_packages/message-list/spec/message-list-spec.cjsx as indicated by @dweremeichik

**Comment by tsikerdekis** [comment]
So turns out there is another sort of tests included in nylas. They used jasmine for their testing kit. The test-client doesnt show much but the test-client-window does show errors and everything else. It also seems to run way more tests. There is also an xml export. 
There are at least 10 errors produced by that testing kit that need to be evaluated. My guess is there is already open issues for these.

**Comment by seesemichaelj** [comment]
@dweremeichik do you want to just close this? Don't think anyone is ever going to make these tests; it's like, ultra-low priority lol

**Comment by dweremeichik** [comment]
On the basis that there are a many more pressing tests that could be written, I agree. Closing, if you disagree @tsikerdekis let me know I'll reopen.
