### ISSUE TITLE
Snap Build 2.1.0

### ISSUE THREAD

**Issue by seesemichaelj** [nylas-mail-lives/nylas-mail#32]
This issue is to change the version to 2.1.0 and build release binaries

**Comment by dweremeichik** [comment]
We should look into Travis releasing to GitHub releases. Also note appveyor needs to be setup for Windows.

**Comment by seesemichaelj** [comment]
Let's open a new issue to introduce automated builds later. let's just get these done manually for now?

**Comment by dweremeichik** [comment]
:+1:

**Comment by ASAPHAANING** [comment]
Is this fork releasing some sort of binaries of at least documentation on how to build? Am I just missing it? :)

**Comment by seesemichaelj** [comment]
We will be releasing binaries "soon" (when someone has time to get auto deployment to work).

There are Linux build instructions at https://github.com/nylas-mail-lives/nylas-mail/blob/master/docs/guide/contributing/installation.md

We don't currently have documentation on building on Windows or Mac (the documentation just hasn't been written yet)

**Comment by ASAPHAANING** [comment]
Great! I might want to contribute, for instance with some auto deployment and it infrastructure, and then move on to backend/frontend, how do I sign up? ;)

**Comment by seesemichaelj** [comment]
I would start by forking this repository and finding an issue https://github.com/nylas-mail-lives/nylas-mail/issues that needs a contributor and work on that. If you work on anything related to the client (99% of it), you'll need to get the code to compile and run before making changes. https://github.com/nylas-mail-lives/nylas-mail/issues/40 may be something you may help contribute to.

I would also get on Slack; you can find the invite url on the README so you can ask these kinds of questions instead of here on the issues

**Comment by seesemichaelj** [comment]
https://github.com/nylas-mail-lives/nylas-mail/releases/tag/2.1.0
