### ISSUE TITLE
Disable Auto-Updater for 2.1.0

### ISSUE THREAD

**Issue by seesemichaelj** [nylas-mail-lives/nylas-mail#34]
We haven't addressed how we're going to do (or even if we'll support) auto-updating. This issue will disable the auto-updater until we can address this properly

**Comment by dweremeichik** [comment]
Can this be closed, or do we want to come up with some ad-hoc way to check GitHub releases and let the user know that a new version is available for download?

**Comment by seesemichaelj** [comment]
Yup! PR #36 addressed this and can be closed.
