### ISSUE TITLE
Add Another Build Command Which Skips Packaging

### ISSUE THREAD

**Issue by seesemichaelj** [nylas-mail-lives/nylas-mail#44]
We should have a build command that skips packaging for Linux/Mac since it's not necessary for development. Perhaps the current "build-client" command would serve this purpose and we make a new command that just does packaging "package-client" or something like that.

**Comment by step21** [comment]
I kinda tried to get this working. It more or less works, except somehow when skipping platform specific packaging, grunt does not accept registering only 'package' or nothing as a task instead of the platform specific packaging. Any idea why this could be?

**Comment by dweremeichik** [comment]
I think it should be able to be done simply with `npm start`.

**Comment by step21** [comment]
Well, I based this on the procedure in `docs/guide/contributing/installation.md` This requires manually running `npm build-client`. Do you mean that `npm start` (which is `npm run client`) runs `npm run build-client` automatically?

**Comment by step21** [comment]
After looking into this and confirming with @dweremeichik in another thread, it seems this can be closed as  `build-client`is basically `package-client`. If anything, this should maybe be clarified in the docs, that this does not actually build, but package.

**Comment by seesemichaelj** [comment]
This would mean that you can do `npm start` or `npm run client` without running `npm run build-client` on a fresh clone?

**Comment by step21** [comment]
This should be the case, yes. I can test it again just to be sure.

**Comment by step21** [comment]
Confirmed.

**Comment by seesemichaelj** [comment]
Closed as this issue is not applicable
