### ISSUE TITLE
Create macOS build docs

### ISSUE THREAD

**Issue by docksteaderluke** [nylas-mail-lives/nylas-mail#48]
Build docs need to be created for macOS.

**Comment by dweremeichik** [comment]
I believe that @GrayW has had success building on Mac.

**Comment by KyleKing** [comment]
I can probably help. Here are my WIP notes and I'll compile a PR based on your feedback. 

I'm not entirely sure what dependencies you need, but here is the list that I could think of:

- Install git through Homebrew `brew install git` or just download [Github for Mac](https://desktop.github.com/)
- XCode will install most of what you need (gcc, clang, g++). Download the latest XCode from the App Store then run `xcode-select --install` from terminal to install the CLI tools
- Install NPM and Node through [NVM](https://github.com/creationix/nvm#install-script) and check your versions (below are ones that are known to work)

```bash
npm -v # 3.10.3
node -v # 6.3.1
electron -v # 0.36.2
```

Then clone and build Nylas-Mail (P.S. I've never needed `npm run build-client`? https://github.com/nylas-mail-lives/nylas-mail/issues/44)

```
git clone https://github.com/nylas-mail-lives/nylas-mail.git; cd nylas-mail
npm install; npm run-script postinstall
npm start
```

**Comment by dweremeichik** [comment]
`build-client` packages the app. So it should create a dmg in the client-app/dist folder. For local debugging you should be okay without it. Unless you do want to install it as dog food (what I have been doing).

**Comment by dweremeichik** [comment]
@KyleKing FWIW `postinstall` should be called automatically by npm after you run `npm install`.

**Comment by step21** [comment]
Kind of hijacking this maybe - @dweremeichik are you sure `build-client` only packages? If yes, this might explain my confusion with trying to make a `build-client` command that does not package the app.

**Comment by dweremeichik** [comment]
Here are the grunt tasks that get called:
https://github.com/nylas-mail-lives/nylas-mail/blob/master/packages/client-app/build/Gruntfile.js#L77-L81

**Comment by step21** [comment]
Thanks, yeah I found that. But I am not very used to node/electron/js stuff this big, so it's all still a bit like magic and I was not sure if I misunderstood the code or it was doing something that I was not aware of.

**Comment by dweremeichik** [comment]
Those tasks live in the task folder, for example: https://github.com/nylas-mail-lives/nylas-mail/blob/master/packages/client-app/build/tasks/package-task.js

**Comment by step21** [comment]
Thanks. Same applies, I was not sure it was maybe doing something I did not understand/was not aware of. But now verified it, and `build-client` is only responsible for packaging, so this can be mentioned in docs.

**Comment by kontrollanten** [comment]
I can build and run the app on Mac. But some of the tests during `npm run test-client`. Is it supposed to be like that? If it is, then I can make a PR about how to set up dev env on Mac

**Comment by step21** [comment]
@kontrollanten I think that is not related to mac. At least for me on Linux some tests also fail.
