### ISSUE TITLE
State what is this fork and what it intends to accomplish

### ISSUE THREAD

**Issue by danielmelogpi** [nylas-mail-lives/nylas-mail#5]
Extend the readme and explain *why the fork?* ..

**Comment by danielmelogpi** [comment]
will do this later and submit a PR

**Comment by dolanor** [comment]
A tool that could be useful : 
https://github-issue-mover.appspot.com/
And for PR's, we can do it manually with git black magic (I don't remember how and don't have time to check it right now, but I know you can fetch PR in your local repo, then you just have to push to a new branch and create a PR out of it.)

**Comment by dweremeichik** [comment]
PR merged, good to close?

**Comment by danielmelogpi** [comment]
I squashed all of those edits into my fork but, since you already merged, let's close this.
