### ISSUE TITLE
Unsubscribe settings not showing.

### ISSUE THREAD

**Issue by dweremeichik** [nylas-mail-lives/nylas-mail#50]
Noticed after merging that I can't find the settings for the unsubscribe plugin (I built and installed the deb locally). See PR #49. cc @KyleKing

**Comment by KyleKing** [comment]
I just built from a fresh clone and was able to see the settings page. Below are the commands that I ran for Mac Sierra (10.12.6)

```bash
git clone https://github.com/nylas-mail-lives/nylas-mail.git; cd nylas-mail
npm install; npm run-script postinstall
npm start
```

<img width="1440" alt="nylas mail electron today at 08 53 22" src="https://user-images.githubusercontent.com/3784339/28753600-ccc8ab52-7504-11e7-9fc6-86bf2faf1d98.png">
<img width="1440" alt="nylas mail electron today at 08 54 04" src="https://user-images.githubusercontent.com/3784339/28753601-ceea1d4e-7504-11e7-9f76-2acafb62994a.png">

**Comment by dweremeichik** [comment]
Thanks @KyleKing. I think I did something dumb, or had something cached. It appears to work for me now.
