### ISSUE TITLE
Location of email database on Mac sierra 

### ISSUE THREAD

**Issue by yoshiserry** [nylas-mail-lives/nylas-mail#57]
##### Are there any related issues.
related issues to my knowledge. 
##### What operating system are you using?
Osx sierra
##### What version of Nylas Mail are you using?
2. Something
**Feature Request?**
##### Does this feature exist in another mail client or tool you use. 
Thus feature does not exist at least completely in any other email client though is partially available in Outlook through VBA scripting

**Comment by seesemichaelj** [comment]
I'm confused what this issue is about? Is this a question asking for the location of the email database?

**Comment by yoshiserry** [comment]
yes this is a question asking for the location of the email database. I'd like to use it to work out a list of all senders and recipients of email to my account. sorry wasn't sure of the best place to put this.

**Comment by seesemichaelj** [comment]
The best place would to ask inside our Slack channel. The invite link can be found at the top of the readme; I have pasted it for ease of use: https://join.slack.com/nylasisalive/shared_invite/MjAzMDE1NTU0MDM2LTE0OTgyNzM3MTItODY4OWNlNTdkMw

Closing this issue due to not being a valid issue.
