### ISSUE TITLE
Folder IMAP, Sent, Drafts...

### ISSUE THREAD

**Issue by Aleixenandros** [nylas-mail-lives/nylas-mail#64]
I do not have the option to select which folder is sent. I used to be.

Is it possible to add it again?

**Comment by seesemichaelj** [comment]
I'm confused what you mean, can you elaborate?

**Comment by Aleixenandros** [comment]
I can not select the Sent and Deleted folder on my IMAP server
![imagen](https://user-images.githubusercontent.com/31532028/29976556-b4916e34-8f3a-11e7-862e-d4e28a824959.png)

**Comment by Aleixenandros** [comment]
See:
https://github.com/nylas/nylas-mail/issues/1457
This has already been soluced, but now it is not

**Comment by seesemichaelj** [comment]
unfortunately the fix put in https://github.com/nylas/nylas-mail/issues/1457 did not get put into github which is why it doesn't work in our branch. we'll see if we can look at the history in that issue and figure out what they did to fix it and implement it

**Comment by Aleixenandros** [comment]
Gracias!

**Comment by dweremeichik** [comment]
@seesemichaelj that fix should be in the Nylas code dump.

**Comment by Aleixenandros** [comment]
It is already fixed in the latest version

Thanks!!!!

**Comment by seesemichaelj** [comment]
Awesome!
