### ISSUE TITLE
Can not display mail from Amazon (HTML-mail?)

### ISSUE THREAD

**Issue by kometchtech** [nylas-mail-lives/nylas-mail#72]
##### Are there any related issues?

...
https://github.com/nylas/nylas-mail/issues/3434
##### What operating system are you using?
...
Windows 10 Pro 1703 x64
##### What version of Nylas Mail are you using?
...
2.1.0
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
It does not appear to be related to a specific mail provider.
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
All text from Amazon will not be displayed.
![capture](https://user-images.githubusercontent.com/5137077/30512589-f401a54e-9b2d-11e7-87d3-3d7d92437740.PNG)
--

**Comment by dweremeichik** [comment]
Thanks for creating an issue. A few questions to try to reproduce. Is this the JP domain only? Are these receipts from amazon? Who is your mail provider?

**Comment by kometchtech** [comment]
@dweremeichik 

Hello,

I'm sorry. Since I have never shopped on Amazon.com etc, I have never checked any situation other than JP domain.

As you say, all e-mails coming from Amazon.co.jp are in this situation.

By the way, I am using gmail for mails that I am receiving, and there are no problems displayed there. Also, I attached it as E-mail to the topic, but confirmed this problem by text mail.

Best regards.

**Comment by dweremeichik** [comment]
Another troubleshooting tip/fun fact, in between the date and reply button there is a hidden (invisible) button that you can click to show the original message, in the format that Nylas received it. 
![screenshot from 2017-09-16 11 05 25](https://user-images.githubusercontent.com/4079608/30513333-650c4ad2-9acf-11e7-9620-96611d7572a7.jpeg)

**Comment by kometchtech** [comment]
I did not know this function.

Using "show original", it was like this.

We convert what is displayed into a text file.

[mail.txt](https://github.com/nylas-mail-lives/nylas-mail/files/1308410/mail.txt)

**Comment by seesemichaelj** [comment]
FYI, amazon.com emails have no issue. We'll take a look at your text file

**Comment by kometchtech** [comment]
@seesemichaelj 

Thank you for information.

If there is any other necessary information, please contact us.
