### ISSUE TITLE
Unable to log in to Gmail or Outlook with avast

### ISSUE THREAD

**Issue by sGerli** [nylas-mail-lives/nylas-mail#74]
This feature was added in Nylas 2.0.18 to fix this issue but currently I don't see it in this fork's 2.1.:
- Allow bypassing of invalid certificates during authentication

And because of the lack of it I get: `Please contact support@nylas.com. An unforeseen error has occurred.`

##### Are there any related issues?
No

##### What operating system are you using?
Windows 10

##### What version of Nylas Mail are you using?
2.1.0

--

**Bug?** Yes
##### Do you have any third-party plugins installed? If so, which ones?
None (also because of a bug)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail and outlook

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Just install avast free and enable mail filter

**Comment by dweremeichik** [comment]
If this was in a pre existing build, you should see the fix/work around in the upcoming release.

**Comment by seesemichaelj** [comment]
The latest release should hopefully fix this. Let us know if it works https://github.com/nylas-mail-lives/nylas-mail/releases/tag/2.2.0

**Comment by sGerli** [comment]
Yes, this update/rebase fixed it.
