### ISSUE TITLE
No sound when notify

### ISSUE THREAD

**Issue by kometchtech** [nylas-mail-lives/nylas-mail#76]
##### Are there any related issues?

...
https://github.com/nylas/nylas-mail/issues/3477
##### What operating system are you using?
...
Windows 10 Pro 1703
##### What version of Nylas Mail are you using?
...
2.1.0
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
Gmail and Company's mail server
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
There was no problem when using at least 2.0.32.
I tried reinstalling 2.1.0, but the situation did not change.
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by seesemichaelj** [comment]
Please remember that 2.1.0 is based off of 2.0.15, not 2.0.32 (due to lack of software). 2.2.0 will be based off the latest 2.0.32 changes from Nylas

Otherwise, you need to be a little more descriptive as we're not sure what the issue really is.

**Comment by kometchtech** [comment]
I acknowledged it.

When we introduce 2.2.0 which will be released in the future, we will confirm again and report on whether this problem will be solved.

Thanks.

**Comment by seesemichaelj** [comment]
Just released! https://github.com/nylas-mail-lives/nylas-mail/releases/tag/2.2.0

**Comment by kometchtech** [comment]
When installing NylasMailSetup-2.2.0-x64.exe, it was confirmed that the sound is heard when it is notify without any problem.

Thanks.
