### ISSUE TITLE
[GMAIL] - IMAP support...

### ISSUE THREAD

**Issue by diegomachadosoares** [nylas-mail-lives/nylas-mail#89]
Hey Guys. Is there any reason why gmail.com can't be (explicitly) configured using simple IMAP?
Since IMAP configuration doesn't call n1.nylas.com anymore (thanks @simonft!) it is useful (for privacy sake) to be able to configure gmail accounts through IMAP. 

Also as pointed by @simonft on Slack channel, the block is hard coded here:

https://github.com/nylas-mail-lives/nylas-mail/blob/master/packages/client-app/internal_packages/onboarding/lib/page-account-settings-imap.jsx#L42-L45

So it should be simple to remove the block and configure gmail accounts through IMAP (as long as the gmail account is also configured to "less secure" access, of course).

**Comment by dweremeichik** [comment]
I'm :+1: on this functionality, it would be a great hacktoberfest issue for someone!

**Comment by diegomachadosoares** [comment]
I'm on it... I'll try removing the block and post something ASAP... Happy Hacktoberfest! ;-)

**Comment by seesemichaelj** [comment]
I'm definitely cool with allowing IMAP for Gmail as long as we're not getting rid of the default functionality; it doesn't appear that's what your'e doing though!
