### ISSUE TITLE
Allow Anonymous IMAP/SMTP relays

### ISSUE THREAD

**Issue by cvharris** [nylas-mail-lives/nylas-mail#94]
I have an exchange account that throws a `504 5.7.4 Unrecognized authentication type` error when trying to connect to it with auth in the nodemailer transport config. Its security relies on network connection, not username/password.

IMAP/SMTP settings should be allowed to be submitted without requiring username and password.

If someone can confirm this is a good feature to have, I can put together a PR for it

**Comment by dweremeichik** [comment]
I would think that this is an uncommon situation to find oneself in. However, as odd as it may be I understand it's merit. Perhaps this should have it's own section as "Anonymous Relay" instead of removing the password requirements on "IMAP / SMTP". @seesemichaelj what are your thoughts?

**Comment by seesemichaelj** [comment]
i would say the percentage of people to use this functionality will be super low though, but I don't think it's unreasonable

**Comment by dweremeichik** [comment]
Perhaps you are correct on not having a separate area. My thoughts are: a lot of people use this for the simplicity, and for many people, setting up their email is daunting. I think requiring a password is a good idea, secure by default. Perhaps a compromise is a checkbox for expert mode that removes all of those checks when ticked.

**Comment by seesemichaelj** [comment]
I could be okay with the checkbox; I'm just not sure how intuitive it is to the user that checking that box stops doing checks? I'm not sure

**Comment by dweremeichik** [comment]
Perhaps I'm reading into this one a little too much.

**Comment by dweremeichik** [comment]
Seems not requiring a password makes sense. However in the event that Nylas can't authenticate to a provider it should show a warning that a password may be needed (if there is no password entered).

**Comment by seesemichaelj** [comment]
Sorry if I didn't steal your thunder @cvharris, but I went ahead and implemented this. I'm not quite sure how to test to see if it works. I guess you can either build with it or test it when we put out v2.2.2. We can consider this issue closed after merge unless we discover it still doesnt work
