### ISSUE TITLE
Does the project go forward?

### ISSUE THREAD

**Issue by Aleixenandros** [nylas-mail-lives/nylas-mail#96]
I have seen this:

> Mailspring is a Nylas fork created by one of the apps original developers. It’s said to be ‘faster’ and ‘leaner’ than the version its based.

https://github.com/Foundry376/Mailspring

**Comment by seesemichaelj** [comment]
Mailspring is a separate fork of Nylas maintained by one of the ex-Nylas Mail devs. It is similar but different from this repo (NML). You can see more discussion on this repo on issue #52.

Mailspring has a closed source sync engine so those with privacy/trust concerns will still find use with NML. With that said, many people and devs will be shifting support to Mailspring as it may be potentially funded and faster than NML. However, despite the recent "release" of Mailspring, it isn't quite yet stable.

So take it as you will. There is a potential future that there will be two separate repos/projects.

**Comment by Aleixenandros** [comment]
Me quedo por aquí mejor
