### ISSUE TITLE
back up and fork Mailspring instead?

### ISSUE THREAD

**Issue by lamixer** [nylas-mail-lives/nylas-mail#97]
https://github.com/Foundry376/Mailspring

Sorry if this is inappropriate to post here in Github, as it's not really an issue. But, if it is correct that Ben Gotow has made significant under-the-hood improvements to the operation of Nylas Mail and open-sourced his improvements, maybe you should backup and fork Mailspring and remove the proprietary backend stuff so we could all enjoy using it as a normal imap mail client?

**Comment by seesemichaelj** [comment]
Please see #52 and #96 

Mailspring is a different and separate project. It is based off 2.0.15 of Nylas Mail (NML is based off of 2.0.32) that adds a c++ closed source mail sync. So in it's nature, NML *is* already what you're asking. If you want to use Mailspring, support that repo and not this repo. If you want an open source mail client stay here. There's nothing we can pull from Mailspring that we don't already have that isn't their closed source sync.

**Comment by lamixer** [comment]
Great. Got it. Thanks. I hope you are in a position to release something soon! I look forward to it very much.

**Comment by seesemichaelj** [comment]
Did you check out the Releases tab on the main page of the repo? We've released two NML versions already. Check out https://github.com/nylas-mail-lives/nylas-mail/releases/

**Comment by lamixer** [comment]
Ah... I (foolishly) didn't look at the code tab there. I stopped when in the ReadMe (on Github main page) where the "Download Nylas Mail" says you are still figuring out your deployment options. I'll try the RPM!

**Comment by seesemichaelj** [comment]
Ya it's a little hidden; I think it'd be smart to put the link near the top of our readme!

Let us know if you have any issues with the RPM; I don't think anyone has tested that package yet.

**Comment by lamixer** [comment]
ok.. actually I decided to clone the repo. I just installed nodejs and npm and am trying to figure out how to run it! Maybe at some point you can post some instructions for dummies. 

My current state of affairs is

"Failed at the nylas-mail-all@0.0.1 lint-client script 'grunt lint --gruntfile=packages/client-app/build/Gruntfile.js --base=./'."

but it's still early...

**Comment by seesemichaelj** [comment]
https://github.com/nylas-mail-lives/nylas-mail/blob/master/docs/guide/contributing/installation.md is what weve got so far

redis isnt required
