### ISSUE TITLE
Update Readme with Releases Link

### ISSUE THREAD

**Issue by seesemichaelj** [nylas-mail-lives/nylas-mail#98]
The readme has a download section that currently says we haven't released yet. We need to update this pointing them to https://github.com/nylas-mail-lives/nylas-mail/releases

**Comment by dweremeichik** [comment]
Will do shortly.

**Comment by diegomachadosoares** [comment]
@dweremeichik, I was about to propose this change... You could add the link to the right AUR package for Archlinux wiich is [this](https://aur.archlinux.org/packages/nylas-mail-lives-bin)...

**Comment by diegomachadosoares** [comment]
Also I think that the download of the unmaintained version should not be encouraged, so maybe you could remove the reference to nylas.com/download from this sections, what you think?

**Comment by dweremeichik** [comment]
Fixed!
