### ISSUE TITLE
client doesn't start -- Fedora, from source

### ISSUE THREAD

**Issue by lamixer** [nylas-mail-lives/nylas-mail#99]
Hello ... Nodejs is like another world for me, so it's entirely possible I have some environment problem. I cloned the repo today (5 Oct 2017), installed nodejs and npm from Fedora 26 standard repos, and eventually got a successful npm install (after realising a sudo is needed there).

node v6.11.3
npm  v3.10.10

Now a 'npm start' or 'npm run client' results in the following output, but no application appearing:
```
[me@xps nylas-mail]$ npm start

> nylas-mail-all@0.0.1 start /home/me/Documents/Nylas-Mail-Git/nylas-mail
> npm run client

> nylas-mail-all@0.0.1 client /home/me/Documents/Nylas-Mail-Git/nylas-mail
> node scripts/run-client-app --enable-logging --dev
```
and 
```
[me@xps nylas-mail]$ npm run lint-client
```
shows 17 errors then ends with
```
Warning: Task "eslint:target" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.12.14-300.fc26.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "lint-client"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! nylas-mail-all@0.0.1 lint-client: `grunt lint --gruntfile=packages/client-app/build/Gruntfile.js --base=./`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the nylas-mail-all@0.0.1 lint-client script 'grunt lint --gruntfile=packages/client-app/build/Gruntfile.js --base=./'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nylas-mail-all package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt lint --gruntfile=packages/client-app/build/Gruntfile.js --base=./
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nylas-mail-all
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nylas-mail-all
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/me/Documents/Nylas-Mail-Git/nylas-mail/npm-debug.log
```

any hints spring to mind?  I understand this more of a support request than a but report as I'm sure with more technical knowlege or node experience this works just fine. Thank you!

**Comment by seesemichaelj** [comment]
Btw, we do have a Slack channel (invite URL in the readme) which these kinds of questions could be asked as well

**Comment by seesemichaelj** [comment]
The install instructions do state to use 6.9 of node, not 6.11 (although I've gotten 6.11 to work)

**Comment by seesemichaelj** [comment]
I would also give the RPM a try

**Comment by lamixer** [comment]
yes. I surrender to node and its shenanigans.

**Comment by lamixer** [comment]
by the way, the RPM worked great on Fedora 26, no additional dependencies needed to be installed.

**Comment by ruffson** [comment]
How do I obtain the RPM? I tried running `npm run build-client` in F27 but I got errors.

```
> nylas-mail-all@0.0.1 build-client /home/user/Apps/Nylas
> grunt build-client --gruntfile=packages/client-app/build/Gruntfile.js --base=./

Loading "docs-build-task.js" tasks...ERROR
>> Error: Cannot find module 'donna'
Loading "docs-render-task.js" tasks...ERROR
>> Error: Cannot find module 'handlebars'
Loading "docs-task.js" tasks...ERROR
>> Error: Cannot find module 'donna'
Loading "package-task.js" tasks...ERROR
>> Error: Cannot find module 'coffee-react'
Warning: Task "package" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! nylas-mail-all@0.0.1 build-client: `grunt build-client --gruntfile=packages/client-app/build/Gruntfile.js --base=./`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the nylas-mail-all@0.0.1 build-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by seesemichaelj** [comment]
@ruffson probably should have opened a new issue instead of necrobumping this one, but no worries!

Did you check out the Releases tab? https://github.com/nylas-mail-lives/nylas-mail/releases/latest has an RPM

If you want to compile it yourself, did you follow the instructions at https://github.com/nylas-mail-lives/nylas-mail/blob/master/docs/guide/contributing/installation.md? You'll need to change the `apt-get` commands to `yum` commands.

**Comment by ruffson** [comment]
Okay I was not aware of these binaries. Thank you!
